### ISSUE TITLE
Error 401 for nested forms in the form builder

### ISSUE THREAD

**Issue by dcoevoet51** [DigitalState/Forms#34]
Hello, 

It is impossible to use nested forms in the form builder. It can't get the other forms, a 401 error is always returned when I access the form tab of this component.

Details about the error: 
Request URL: https://api.form.io/form?limit=4294967295&select=_id,title
Request Method: GET
Status Code: 401 Unauthorized

Is it possible to correct this problem?

Thanks by advance,

**Comment by StephenOTT** [comment]
Nested forms in the way formio manages their forms is not supported in our build. 

The reason is a lack of control of versioning and access with the control of placeholder values
